#!/usr/bin/env bash
# This script reads and displays the content of the file /etc/passwd

filename="/etc/passwd"

while IFS=: read -r username _ uid _ _ home _; do
    echo "$username:$uid:$home"
done < "$filename"

