#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
# Get the list of processes and format the output
ps -ef --forest --no-headers --sort=start_time | awk "{ printf "%-10s %-5s %-4s %-4s %-6s %-5s %-8s %-4s %-6s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10 }"

