#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
ps aux --forest | awk '{printf "%-10s %5s %4s %4s %6s %5s %-9s %4s %s %s", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10; for (i=11; i<=NF; i++) printf " %s", $i; printf "\n"}' | head -50
