#!/usr/bin/env bash
# This script runs indefinitely, displaying messages and responding to signals.

# Create the PID file
echo $$ > /var/run/myscript.pid

# Function to handle SIGTERM and SIGQUIT signals
function handle_sigterm {
    echo "I hate the kill command"
    cleanup_and_exit
}

# Function to handle SIGINT signal
function handle_sigint {
    echo "Y U no love me?!"
}

# Function to delete the PID file and exit
function cleanup_and_exit {
    rm /var/run/myscript.pid
    exit
}

# Register signal handlers
trap 'handle_sigterm' SIGTERM SIGQUIT
trap 'handle_sigint' SIGINT

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

