#!/usr/bin/env bash
# This script runs indefinitely, displaying messages and responding to signals.

# Create the PID file
echo $$ > /var/run/myscript.pid

# Function to handle SIGTERM signal
function handle_sigterm {
    echo "I hate the kill command"
}

# Function to handle SIGINT signal
function handle_sigint {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
function handle_sigquit {
    # Delete the PID file
    rm /var/run/myscript.pid
    exit
}

# Register signal handlers
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

