#!/usr/bin/env bash
#This script manages the manage_my_process script

PID_FILE="/var/run/my_process.pid"

start_process() {
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process is already running."
    else
        ./manage_my_process &
        echo $! > "$PID_FILE"
        echo "manage_my_process started."
    fi
}

stop_process() {
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE")
        kill "$pid"
        rm "$PID_FILE"
        echo "manage_my_process stopped."
    else
        echo "manage_my_process is not running."
    fi
}

restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted."
}

if [ $# -eq 0 ]; then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

