#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep of 2 seconds in between each iteration.
# It displays "OK" when receiving a SIGTERM signal.
trap "echo  I am invincible!!!" SIGTERM
while true; do
  echo "To infinity and beyond"
  sleep 2
done

