#!/usr/bin/env bash
# This script kills the '7-highlander' process.

# Find the process ID (PID) of '7-highlander'
pid=$(pgrep -f '7-highlander')

# Check if the process is running
if [ -n "$pid" ]; then
  # Kill the '7-highlander' process
  kill "$pid" &>/dev/null
fi

