#!/usr/bin/env bash
# This script indefinitely writes "I am alive!" to the file /tmp/my_process
# It pauses for 2 seconds between every message

while true; do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
